### ISSUE TITLE
pull posts from wp main website

### ISSUE THREAD

**Issue by claudioccm** [GovLab/noi-site#1]
This is the category from the wp site: Featured NOI (ID 500)

We need to pull just the excerpt. We **don't** want to show a "READ MORE" button, since we want people to signup to read the content.

**Comment by ghost** [comment]
If this is coming from our wp install, we do need to set up jetpack in order to use the api, lemme ping cheis

**Comment by ghost** [comment]
https://github.com/GovLab/noi-site/pull/3

**Comment by ghost** [comment]
this was done
